# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/Demonstrations

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/Demonstrations

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/Demonstrations/CMakeFiles /Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/Demonstrations//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/Demonstrations/CMakeFiles 0
.PHONY : all

# The main codegen target
codegen: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/Demonstrations/CMakeFiles /Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/Demonstrations//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 codegen
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/Demonstrations/CMakeFiles 0
.PHONY : codegen

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named freertos_kernel

# Build rule for target.
freertos_kernel: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 freertos_kernel
.PHONY : freertos_kernel

# fast build rule for target.
freertos_kernel/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/freertos_kernel.dir/build.make CMakeFiles/freertos_kernel.dir/build
.PHONY : freertos_kernel/fast

#=============================================================================
# Target rules for targets named stm32.elf

# Build rule for target.
stm32.elf: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 stm32.elf
.PHONY : stm32.elf

# fast build rule for target.
stm32.elf/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/build
.PHONY : stm32.elf/fast

Drivers/BSP/Components/lis302dl/lis302dl.o: Drivers/BSP/Components/lis302dl/lis302dl.c.o
.PHONY : Drivers/BSP/Components/lis302dl/lis302dl.o

# target to build an object file
Drivers/BSP/Components/lis302dl/lis302dl.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/BSP/Components/lis302dl/lis302dl.c.o
.PHONY : Drivers/BSP/Components/lis302dl/lis302dl.c.o

Drivers/BSP/Components/lis302dl/lis302dl.i: Drivers/BSP/Components/lis302dl/lis302dl.c.i
.PHONY : Drivers/BSP/Components/lis302dl/lis302dl.i

# target to preprocess a source file
Drivers/BSP/Components/lis302dl/lis302dl.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/BSP/Components/lis302dl/lis302dl.c.i
.PHONY : Drivers/BSP/Components/lis302dl/lis302dl.c.i

Drivers/BSP/Components/lis302dl/lis302dl.s: Drivers/BSP/Components/lis302dl/lis302dl.c.s
.PHONY : Drivers/BSP/Components/lis302dl/lis302dl.s

# target to generate assembly for a file
Drivers/BSP/Components/lis302dl/lis302dl.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/BSP/Components/lis302dl/lis302dl.c.s
.PHONY : Drivers/BSP/Components/lis302dl/lis302dl.c.s

Drivers/BSP/Components/lis3dsh/lis3dsh.o: Drivers/BSP/Components/lis3dsh/lis3dsh.c.o
.PHONY : Drivers/BSP/Components/lis3dsh/lis3dsh.o

# target to build an object file
Drivers/BSP/Components/lis3dsh/lis3dsh.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/BSP/Components/lis3dsh/lis3dsh.c.o
.PHONY : Drivers/BSP/Components/lis3dsh/lis3dsh.c.o

Drivers/BSP/Components/lis3dsh/lis3dsh.i: Drivers/BSP/Components/lis3dsh/lis3dsh.c.i
.PHONY : Drivers/BSP/Components/lis3dsh/lis3dsh.i

# target to preprocess a source file
Drivers/BSP/Components/lis3dsh/lis3dsh.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/BSP/Components/lis3dsh/lis3dsh.c.i
.PHONY : Drivers/BSP/Components/lis3dsh/lis3dsh.c.i

Drivers/BSP/Components/lis3dsh/lis3dsh.s: Drivers/BSP/Components/lis3dsh/lis3dsh.c.s
.PHONY : Drivers/BSP/Components/lis3dsh/lis3dsh.s

# target to generate assembly for a file
Drivers/BSP/Components/lis3dsh/lis3dsh.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/BSP/Components/lis3dsh/lis3dsh.c.s
.PHONY : Drivers/BSP/Components/lis3dsh/lis3dsh.c.s

Drivers/BSP/STM32F4-Discovery/stm32f4_discovery.o: Drivers/BSP/STM32F4-Discovery/stm32f4_discovery.c.o
.PHONY : Drivers/BSP/STM32F4-Discovery/stm32f4_discovery.o

# target to build an object file
Drivers/BSP/STM32F4-Discovery/stm32f4_discovery.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/BSP/STM32F4-Discovery/stm32f4_discovery.c.o
.PHONY : Drivers/BSP/STM32F4-Discovery/stm32f4_discovery.c.o

Drivers/BSP/STM32F4-Discovery/stm32f4_discovery.i: Drivers/BSP/STM32F4-Discovery/stm32f4_discovery.c.i
.PHONY : Drivers/BSP/STM32F4-Discovery/stm32f4_discovery.i

# target to preprocess a source file
Drivers/BSP/STM32F4-Discovery/stm32f4_discovery.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/BSP/STM32F4-Discovery/stm32f4_discovery.c.i
.PHONY : Drivers/BSP/STM32F4-Discovery/stm32f4_discovery.c.i

Drivers/BSP/STM32F4-Discovery/stm32f4_discovery.s: Drivers/BSP/STM32F4-Discovery/stm32f4_discovery.c.s
.PHONY : Drivers/BSP/STM32F4-Discovery/stm32f4_discovery.s

# target to generate assembly for a file
Drivers/BSP/STM32F4-Discovery/stm32f4_discovery.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/BSP/STM32F4-Discovery/stm32f4_discovery.c.s
.PHONY : Drivers/BSP/STM32F4-Discovery/stm32f4_discovery.c.s

Drivers/BSP/STM32F4-Discovery/stm32f4_discovery_accelerometer.o: Drivers/BSP/STM32F4-Discovery/stm32f4_discovery_accelerometer.c.o
.PHONY : Drivers/BSP/STM32F4-Discovery/stm32f4_discovery_accelerometer.o

# target to build an object file
Drivers/BSP/STM32F4-Discovery/stm32f4_discovery_accelerometer.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/BSP/STM32F4-Discovery/stm32f4_discovery_accelerometer.c.o
.PHONY : Drivers/BSP/STM32F4-Discovery/stm32f4_discovery_accelerometer.c.o

Drivers/BSP/STM32F4-Discovery/stm32f4_discovery_accelerometer.i: Drivers/BSP/STM32F4-Discovery/stm32f4_discovery_accelerometer.c.i
.PHONY : Drivers/BSP/STM32F4-Discovery/stm32f4_discovery_accelerometer.i

# target to preprocess a source file
Drivers/BSP/STM32F4-Discovery/stm32f4_discovery_accelerometer.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/BSP/STM32F4-Discovery/stm32f4_discovery_accelerometer.c.i
.PHONY : Drivers/BSP/STM32F4-Discovery/stm32f4_discovery_accelerometer.c.i

Drivers/BSP/STM32F4-Discovery/stm32f4_discovery_accelerometer.s: Drivers/BSP/STM32F4-Discovery/stm32f4_discovery_accelerometer.c.s
.PHONY : Drivers/BSP/STM32F4-Discovery/stm32f4_discovery_accelerometer.s

# target to generate assembly for a file
Drivers/BSP/STM32F4-Discovery/stm32f4_discovery_accelerometer.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/BSP/STM32F4-Discovery/stm32f4_discovery_accelerometer.c.s
.PHONY : Drivers/BSP/STM32F4-Discovery/stm32f4_discovery_accelerometer.c.s

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.o: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.c.o
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.o

# target to build an object file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.c.o
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.c.o

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.i: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.c.i
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.i

# target to preprocess a source file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.c.i
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.c.i

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.s: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.c.s
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.s

# target to generate assembly for a file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.c.s
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.c.s

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_adc.o: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_adc.c.o
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_adc.o

# target to build an object file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_adc.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_adc.c.o
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_adc.c.o

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_adc.i: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_adc.c.i
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_adc.i

# target to preprocess a source file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_adc.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_adc.c.i
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_adc.c.i

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_adc.s: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_adc.c.s
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_adc.s

# target to generate assembly for a file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_adc.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_adc.c.s
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_adc.c.s

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_can.o: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_can.c.o
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_can.o

# target to build an object file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_can.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_can.c.o
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_can.c.o

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_can.i: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_can.c.i
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_can.i

# target to preprocess a source file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_can.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_can.c.i
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_can.c.i

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_can.s: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_can.c.s
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_can.s

# target to generate assembly for a file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_can.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_can.c.s
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_can.c.s

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.o: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.c.o
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.o

# target to build an object file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.c.o
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.c.o

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.i: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.c.i
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.i

# target to preprocess a source file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.c.i
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.c.i

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.s: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.c.s
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.s

# target to generate assembly for a file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.c.s
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.c.s

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_crc.o: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_crc.c.o
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_crc.o

# target to build an object file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_crc.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_crc.c.o
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_crc.c.o

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_crc.i: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_crc.c.i
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_crc.i

# target to preprocess a source file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_crc.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_crc.c.i
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_crc.c.i

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_crc.s: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_crc.c.s
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_crc.s

# target to generate assembly for a file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_crc.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_crc.c.s
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_crc.c.s

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cryp.o: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cryp.c.o
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cryp.o

# target to build an object file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cryp.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cryp.c.o
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cryp.c.o

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cryp.i: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cryp.c.i
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cryp.i

# target to preprocess a source file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cryp.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cryp.c.i
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cryp.c.i

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cryp.s: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cryp.c.s
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cryp.s

# target to generate assembly for a file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cryp.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cryp.c.s
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cryp.c.s

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dac.o: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dac.c.o
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dac.o

# target to build an object file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dac.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dac.c.o
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dac.c.o

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dac.i: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dac.c.i
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dac.i

# target to preprocess a source file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dac.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dac.c.i
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dac.c.i

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dac.s: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dac.c.s
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dac.s

# target to generate assembly for a file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dac.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dac.c.s
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dac.c.s

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dcmi.o: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dcmi.c.o
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dcmi.o

# target to build an object file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dcmi.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dcmi.c.o
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dcmi.c.o

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dcmi.i: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dcmi.c.i
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dcmi.i

# target to preprocess a source file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dcmi.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dcmi.c.i
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dcmi.c.i

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dcmi.s: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dcmi.c.s
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dcmi.s

# target to generate assembly for a file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dcmi.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dcmi.c.s
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dcmi.c.s

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma.o: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma.c.o
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma.o

# target to build an object file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma.c.o
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma.c.o

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma.i: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma.c.i
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma.i

# target to preprocess a source file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma.c.i
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma.c.i

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma.s: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma.c.s
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma.s

# target to generate assembly for a file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma.c.s
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma.c.s

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_eth.o: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_eth.c.o
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_eth.o

# target to build an object file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_eth.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_eth.c.o
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_eth.c.o

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_eth.i: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_eth.c.i
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_eth.i

# target to preprocess a source file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_eth.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_eth.c.i
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_eth.c.i

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_eth.s: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_eth.c.s
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_eth.s

# target to generate assembly for a file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_eth.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_eth.c.s
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_eth.c.s

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash.o: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash.c.o
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash.o

# target to build an object file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash.c.o
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash.c.o

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash.i: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash.c.i
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash.i

# target to preprocess a source file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash.c.i
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash.c.i

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash.s: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash.c.s
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash.s

# target to generate assembly for a file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash.c.s
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash.c.s

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ex.o: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ex.c.o
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ex.o

# target to build an object file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ex.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ex.c.o
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ex.c.o

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ex.i: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ex.c.i
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ex.i

# target to preprocess a source file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ex.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ex.c.i
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ex.c.i

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ex.s: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ex.c.s
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ex.s

# target to generate assembly for a file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ex.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ex.c.s
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ex.c.s

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.o: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.c.o
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.o

# target to build an object file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.c.o
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.c.o

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.i: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.c.i
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.i

# target to preprocess a source file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.c.i
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.c.i

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.s: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.c.s
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.s

# target to generate assembly for a file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.c.s
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.c.s

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_hash.o: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_hash.c.o
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_hash.o

# target to build an object file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_hash.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_hash.c.o
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_hash.c.o

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_hash.i: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_hash.c.i
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_hash.i

# target to preprocess a source file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_hash.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_hash.c.i
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_hash.c.i

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_hash.s: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_hash.c.s
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_hash.s

# target to generate assembly for a file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_hash.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_hash.c.s
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_hash.c.s

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_hcd.o: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_hcd.c.o
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_hcd.o

# target to build an object file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_hcd.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_hcd.c.o
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_hcd.c.o

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_hcd.i: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_hcd.c.i
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_hcd.i

# target to preprocess a source file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_hcd.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_hcd.c.i
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_hcd.c.i

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_hcd.s: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_hcd.c.s
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_hcd.s

# target to generate assembly for a file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_hcd.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_hcd.c.s
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_hcd.c.s

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2c.o: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2c.c.o
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2c.o

# target to build an object file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2c.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2c.c.o
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2c.c.o

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2c.i: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2c.c.i
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2c.i

# target to preprocess a source file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2c.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2c.c.i
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2c.c.i

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2c.s: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2c.c.s
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2c.s

# target to generate assembly for a file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2c.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2c.c.s
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2c.c.s

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2s.o: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2s.c.o
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2s.o

# target to build an object file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2s.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2s.c.o
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2s.c.o

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2s.i: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2s.c.i
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2s.i

# target to preprocess a source file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2s.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2s.c.i
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2s.c.i

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2s.s: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2s.c.s
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2s.s

# target to generate assembly for a file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2s.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2s.c.s
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2s.c.s

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_irda.o: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_irda.c.o
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_irda.o

# target to build an object file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_irda.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_irda.c.o
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_irda.c.o

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_irda.i: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_irda.c.i
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_irda.i

# target to preprocess a source file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_irda.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_irda.c.i
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_irda.c.i

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_irda.s: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_irda.c.s
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_irda.s

# target to generate assembly for a file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_irda.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_irda.c.s
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_irda.c.s

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_iwdg.o: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_iwdg.c.o
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_iwdg.o

# target to build an object file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_iwdg.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_iwdg.c.o
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_iwdg.c.o

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_iwdg.i: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_iwdg.c.i
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_iwdg.i

# target to preprocess a source file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_iwdg.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_iwdg.c.i
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_iwdg.c.i

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_iwdg.s: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_iwdg.c.s
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_iwdg.s

# target to generate assembly for a file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_iwdg.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_iwdg.c.s
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_iwdg.c.s

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_nand.o: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_nand.c.o
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_nand.o

# target to build an object file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_nand.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_nand.c.o
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_nand.c.o

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_nand.i: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_nand.c.i
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_nand.i

# target to preprocess a source file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_nand.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_nand.c.i
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_nand.c.i

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_nand.s: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_nand.c.s
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_nand.s

# target to generate assembly for a file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_nand.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_nand.c.s
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_nand.c.s

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_nor.o: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_nor.c.o
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_nor.o

# target to build an object file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_nor.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_nor.c.o
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_nor.c.o

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_nor.i: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_nor.c.i
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_nor.i

# target to preprocess a source file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_nor.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_nor.c.i
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_nor.c.i

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_nor.s: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_nor.c.s
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_nor.s

# target to generate assembly for a file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_nor.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_nor.c.s
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_nor.c.s

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pccard.o: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pccard.c.o
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pccard.o

# target to build an object file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pccard.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pccard.c.o
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pccard.c.o

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pccard.i: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pccard.c.i
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pccard.i

# target to preprocess a source file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pccard.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pccard.c.i
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pccard.c.i

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pccard.s: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pccard.c.s
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pccard.s

# target to generate assembly for a file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pccard.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pccard.c.s
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pccard.c.s

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pcd.o: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pcd.c.o
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pcd.o

# target to build an object file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pcd.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pcd.c.o
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pcd.c.o

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pcd.i: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pcd.c.i
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pcd.i

# target to preprocess a source file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pcd.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pcd.c.i
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pcd.c.i

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pcd.s: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pcd.c.s
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pcd.s

# target to generate assembly for a file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pcd.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pcd.c.s
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pcd.c.s

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pcd_ex.o: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pcd_ex.c.o
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pcd_ex.o

# target to build an object file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pcd_ex.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pcd_ex.c.o
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pcd_ex.c.o

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pcd_ex.i: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pcd_ex.c.i
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pcd_ex.i

# target to preprocess a source file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pcd_ex.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pcd_ex.c.i
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pcd_ex.c.i

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pcd_ex.s: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pcd_ex.c.s
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pcd_ex.s

# target to generate assembly for a file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pcd_ex.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pcd_ex.c.s
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pcd_ex.c.s

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr.o: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr.c.o
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr.o

# target to build an object file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr.c.o
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr.c.o

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr.i: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr.c.i
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr.i

# target to preprocess a source file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr.c.i
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr.c.i

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr.s: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr.c.s
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr.s

# target to generate assembly for a file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr.c.s
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr.c.s

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.o: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.c.o
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.o

# target to build an object file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.c.o
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.c.o

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.i: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.c.i
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.i

# target to preprocess a source file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.c.i
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.c.i

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.s: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.c.s
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.s

# target to generate assembly for a file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.c.s
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.c.s

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rng.o: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rng.c.o
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rng.o

# target to build an object file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rng.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rng.c.o
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rng.c.o

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rng.i: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rng.c.i
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rng.i

# target to preprocess a source file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rng.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rng.c.i
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rng.c.i

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rng.s: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rng.c.s
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rng.s

# target to generate assembly for a file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rng.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rng.c.s
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rng.c.s

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rtc.o: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rtc.c.o
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rtc.o

# target to build an object file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rtc.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rtc.c.o
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rtc.c.o

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rtc.i: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rtc.c.i
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rtc.i

# target to preprocess a source file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rtc.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rtc.c.i
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rtc.c.i

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rtc.s: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rtc.c.s
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rtc.s

# target to generate assembly for a file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rtc.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rtc.c.s
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rtc.c.s

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_sd.o: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_sd.c.o
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_sd.o

# target to build an object file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_sd.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_sd.c.o
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_sd.c.o

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_sd.i: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_sd.c.i
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_sd.i

# target to preprocess a source file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_sd.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_sd.c.i
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_sd.c.i

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_sd.s: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_sd.c.s
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_sd.s

# target to generate assembly for a file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_sd.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_sd.c.s
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_sd.c.s

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_smartcard.o: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_smartcard.c.o
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_smartcard.o

# target to build an object file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_smartcard.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_smartcard.c.o
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_smartcard.c.o

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_smartcard.i: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_smartcard.c.i
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_smartcard.i

# target to preprocess a source file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_smartcard.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_smartcard.c.i
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_smartcard.c.i

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_smartcard.s: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_smartcard.c.s
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_smartcard.s

# target to generate assembly for a file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_smartcard.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_smartcard.c.s
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_smartcard.c.s

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_spi.o: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_spi.c.o
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_spi.o

# target to build an object file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_spi.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_spi.c.o
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_spi.c.o

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_spi.i: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_spi.c.i
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_spi.i

# target to preprocess a source file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_spi.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_spi.c.i
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_spi.c.i

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_spi.s: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_spi.c.s
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_spi.s

# target to generate assembly for a file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_spi.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_spi.c.s
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_spi.c.s

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_sram.o: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_sram.c.o
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_sram.o

# target to build an object file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_sram.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_sram.c.o
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_sram.c.o

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_sram.i: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_sram.c.i
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_sram.i

# target to preprocess a source file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_sram.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_sram.c.i
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_sram.c.i

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_sram.s: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_sram.c.s
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_sram.s

# target to generate assembly for a file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_sram.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_sram.c.s
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_sram.c.s

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim.o: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim.c.o
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim.o

# target to build an object file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim.c.o
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim.c.o

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim.i: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim.c.i
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim.i

# target to preprocess a source file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim.c.i
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim.c.i

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim.s: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim.c.s
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim.s

# target to generate assembly for a file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim.c.s
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim.c.s

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim_ex.o: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim_ex.c.o
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim_ex.o

# target to build an object file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim_ex.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim_ex.c.o
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim_ex.c.o

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim_ex.i: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim_ex.c.i
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim_ex.i

# target to preprocess a source file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim_ex.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim_ex.c.i
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim_ex.c.i

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim_ex.s: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim_ex.c.s
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim_ex.s

# target to generate assembly for a file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim_ex.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim_ex.c.s
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim_ex.c.s

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_uart.o: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_uart.c.o
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_uart.o

# target to build an object file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_uart.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_uart.c.o
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_uart.c.o

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_uart.i: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_uart.c.i
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_uart.i

# target to preprocess a source file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_uart.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_uart.c.i
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_uart.c.i

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_uart.s: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_uart.c.s
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_uart.s

# target to generate assembly for a file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_uart.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_uart.c.s
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_uart.c.s

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_usart.o: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_usart.c.o
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_usart.o

# target to build an object file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_usart.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_usart.c.o
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_usart.c.o

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_usart.i: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_usart.c.i
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_usart.i

# target to preprocess a source file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_usart.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_usart.c.i
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_usart.c.i

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_usart.s: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_usart.c.s
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_usart.s

# target to generate assembly for a file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_usart.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_usart.c.s
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_usart.c.s

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_wwdg.o: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_wwdg.c.o
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_wwdg.o

# target to build an object file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_wwdg.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_wwdg.c.o
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_wwdg.c.o

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_wwdg.i: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_wwdg.c.i
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_wwdg.i

# target to preprocess a source file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_wwdg.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_wwdg.c.i
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_wwdg.c.i

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_wwdg.s: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_wwdg.c.s
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_wwdg.s

# target to generate assembly for a file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_wwdg.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_wwdg.c.s
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_wwdg.c.s

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_fsmc.o: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_fsmc.c.o
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_fsmc.o

# target to build an object file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_fsmc.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_fsmc.c.o
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_fsmc.c.o

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_fsmc.i: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_fsmc.c.i
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_fsmc.i

# target to preprocess a source file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_fsmc.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_fsmc.c.i
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_fsmc.c.i

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_fsmc.s: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_fsmc.c.s
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_fsmc.s

# target to generate assembly for a file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_fsmc.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_fsmc.c.s
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_fsmc.c.s

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_sdmmc.o: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_sdmmc.c.o
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_sdmmc.o

# target to build an object file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_sdmmc.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_sdmmc.c.o
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_sdmmc.c.o

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_sdmmc.i: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_sdmmc.c.i
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_sdmmc.i

# target to preprocess a source file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_sdmmc.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_sdmmc.c.i
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_sdmmc.c.i

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_sdmmc.s: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_sdmmc.c.s
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_sdmmc.s

# target to generate assembly for a file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_sdmmc.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_sdmmc.c.s
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_sdmmc.c.s

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_usb.o: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_usb.c.o
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_usb.o

# target to build an object file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_usb.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_usb.c.o
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_usb.c.o

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_usb.i: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_usb.c.i
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_usb.i

# target to preprocess a source file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_usb.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_usb.c.i
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_usb.c.i

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_usb.s: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_usb.c.s
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_usb.s

# target to generate assembly for a file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_usb.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_usb.c.s
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_usb.c.s

STM32CubeIDE/Application/Startup/startup_stm32f407vgtx.o: STM32CubeIDE/Application/Startup/startup_stm32f407vgtx.s.o
.PHONY : STM32CubeIDE/Application/Startup/startup_stm32f407vgtx.o

# target to build an object file
STM32CubeIDE/Application/Startup/startup_stm32f407vgtx.s.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/STM32CubeIDE/Application/Startup/startup_stm32f407vgtx.s.o
.PHONY : STM32CubeIDE/Application/Startup/startup_stm32f407vgtx.s.o

Src/main.o: Src/main.c.o
.PHONY : Src/main.o

# target to build an object file
Src/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Src/main.c.o
.PHONY : Src/main.c.o

Src/main.i: Src/main.c.i
.PHONY : Src/main.i

# target to preprocess a source file
Src/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Src/main.c.i
.PHONY : Src/main.c.i

Src/main.s: Src/main.c.s
.PHONY : Src/main.s

# target to generate assembly for a file
Src/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Src/main.c.s
.PHONY : Src/main.c.s

Src/stm32f4xx_hal_msp.o: Src/stm32f4xx_hal_msp.c.o
.PHONY : Src/stm32f4xx_hal_msp.o

# target to build an object file
Src/stm32f4xx_hal_msp.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Src/stm32f4xx_hal_msp.c.o
.PHONY : Src/stm32f4xx_hal_msp.c.o

Src/stm32f4xx_hal_msp.i: Src/stm32f4xx_hal_msp.c.i
.PHONY : Src/stm32f4xx_hal_msp.i

# target to preprocess a source file
Src/stm32f4xx_hal_msp.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Src/stm32f4xx_hal_msp.c.i
.PHONY : Src/stm32f4xx_hal_msp.c.i

Src/stm32f4xx_hal_msp.s: Src/stm32f4xx_hal_msp.c.s
.PHONY : Src/stm32f4xx_hal_msp.s

# target to generate assembly for a file
Src/stm32f4xx_hal_msp.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Src/stm32f4xx_hal_msp.c.s
.PHONY : Src/stm32f4xx_hal_msp.c.s

Src/stm32f4xx_it.o: Src/stm32f4xx_it.c.o
.PHONY : Src/stm32f4xx_it.o

# target to build an object file
Src/stm32f4xx_it.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Src/stm32f4xx_it.c.o
.PHONY : Src/stm32f4xx_it.c.o

Src/stm32f4xx_it.i: Src/stm32f4xx_it.c.i
.PHONY : Src/stm32f4xx_it.i

# target to preprocess a source file
Src/stm32f4xx_it.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Src/stm32f4xx_it.c.i
.PHONY : Src/stm32f4xx_it.c.i

Src/stm32f4xx_it.s: Src/stm32f4xx_it.c.s
.PHONY : Src/stm32f4xx_it.s

# target to generate assembly for a file
Src/stm32f4xx_it.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Src/stm32f4xx_it.c.s
.PHONY : Src/stm32f4xx_it.c.s

Src/syscalls.o: Src/syscalls.c.o
.PHONY : Src/syscalls.o

# target to build an object file
Src/syscalls.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Src/syscalls.c.o
.PHONY : Src/syscalls.c.o

Src/syscalls.i: Src/syscalls.c.i
.PHONY : Src/syscalls.i

# target to preprocess a source file
Src/syscalls.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Src/syscalls.c.i
.PHONY : Src/syscalls.c.i

Src/syscalls.s: Src/syscalls.c.s
.PHONY : Src/syscalls.s

# target to generate assembly for a file
Src/syscalls.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Src/syscalls.c.s
.PHONY : Src/syscalls.c.s

Src/sysmem.o: Src/sysmem.c.o
.PHONY : Src/sysmem.o

# target to build an object file
Src/sysmem.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Src/sysmem.c.o
.PHONY : Src/sysmem.c.o

Src/sysmem.i: Src/sysmem.c.i
.PHONY : Src/sysmem.i

# target to preprocess a source file
Src/sysmem.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Src/sysmem.c.i
.PHONY : Src/sysmem.c.i

Src/sysmem.s: Src/sysmem.c.s
.PHONY : Src/sysmem.s

# target to generate assembly for a file
Src/sysmem.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Src/sysmem.c.s
.PHONY : Src/sysmem.c.s

Src/system_stm32f4xx.o: Src/system_stm32f4xx.c.o
.PHONY : Src/system_stm32f4xx.o

# target to build an object file
Src/system_stm32f4xx.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Src/system_stm32f4xx.c.o
.PHONY : Src/system_stm32f4xx.c.o

Src/system_stm32f4xx.i: Src/system_stm32f4xx.c.i
.PHONY : Src/system_stm32f4xx.i

# target to preprocess a source file
Src/system_stm32f4xx.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Src/system_stm32f4xx.c.i
.PHONY : Src/system_stm32f4xx.c.i

Src/system_stm32f4xx.s: Src/system_stm32f4xx.c.s
.PHONY : Src/system_stm32f4xx.s

# target to generate assembly for a file
Src/system_stm32f4xx.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Src/system_stm32f4xx.c.s
.PHONY : Src/system_stm32f4xx.c.s

Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/croutine.o: Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/croutine.c.o
.PHONY : Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/croutine.o

# target to build an object file
Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/croutine.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/freertos_kernel.dir/build.make CMakeFiles/freertos_kernel.dir/Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/croutine.c.o
.PHONY : Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/croutine.c.o

Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/croutine.i: Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/croutine.c.i
.PHONY : Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/croutine.i

# target to preprocess a source file
Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/croutine.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/freertos_kernel.dir/build.make CMakeFiles/freertos_kernel.dir/Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/croutine.c.i
.PHONY : Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/croutine.c.i

Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/croutine.s: Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/croutine.c.s
.PHONY : Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/croutine.s

# target to generate assembly for a file
Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/croutine.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/freertos_kernel.dir/build.make CMakeFiles/freertos_kernel.dir/Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/croutine.c.s
.PHONY : Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/croutine.c.s

Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/event_groups.o: Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/event_groups.c.o
.PHONY : Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/event_groups.o

# target to build an object file
Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/event_groups.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/freertos_kernel.dir/build.make CMakeFiles/freertos_kernel.dir/Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/event_groups.c.o
.PHONY : Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/event_groups.c.o

Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/event_groups.i: Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/event_groups.c.i
.PHONY : Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/event_groups.i

# target to preprocess a source file
Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/event_groups.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/freertos_kernel.dir/build.make CMakeFiles/freertos_kernel.dir/Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/event_groups.c.i
.PHONY : Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/event_groups.c.i

Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/event_groups.s: Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/event_groups.c.s
.PHONY : Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/event_groups.s

# target to generate assembly for a file
Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/event_groups.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/freertos_kernel.dir/build.make CMakeFiles/freertos_kernel.dir/Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/event_groups.c.s
.PHONY : Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/event_groups.c.s

Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/list.o: Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/list.c.o
.PHONY : Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/list.o

# target to build an object file
Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/list.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/freertos_kernel.dir/build.make CMakeFiles/freertos_kernel.dir/Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/list.c.o
.PHONY : Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/list.c.o

Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/list.i: Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/list.c.i
.PHONY : Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/list.i

# target to preprocess a source file
Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/list.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/freertos_kernel.dir/build.make CMakeFiles/freertos_kernel.dir/Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/list.c.i
.PHONY : Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/list.c.i

Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/list.s: Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/list.c.s
.PHONY : Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/list.s

# target to generate assembly for a file
Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/list.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/freertos_kernel.dir/build.make CMakeFiles/freertos_kernel.dir/Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/list.c.s
.PHONY : Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/list.c.s

Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/queue.o: Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/queue.c.o
.PHONY : Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/queue.o

# target to build an object file
Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/queue.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/freertos_kernel.dir/build.make CMakeFiles/freertos_kernel.dir/Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/queue.c.o
.PHONY : Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/queue.c.o

Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/queue.i: Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/queue.c.i
.PHONY : Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/queue.i

# target to preprocess a source file
Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/queue.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/freertos_kernel.dir/build.make CMakeFiles/freertos_kernel.dir/Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/queue.c.i
.PHONY : Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/queue.c.i

Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/queue.s: Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/queue.c.s
.PHONY : Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/queue.s

# target to generate assembly for a file
Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/queue.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/freertos_kernel.dir/build.make CMakeFiles/freertos_kernel.dir/Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/queue.c.s
.PHONY : Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/queue.c.s

Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/stream_buffer.o: Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/stream_buffer.c.o
.PHONY : Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/stream_buffer.o

# target to build an object file
Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/stream_buffer.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/freertos_kernel.dir/build.make CMakeFiles/freertos_kernel.dir/Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/stream_buffer.c.o
.PHONY : Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/stream_buffer.c.o

Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/stream_buffer.i: Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/stream_buffer.c.i
.PHONY : Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/stream_buffer.i

# target to preprocess a source file
Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/stream_buffer.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/freertos_kernel.dir/build.make CMakeFiles/freertos_kernel.dir/Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/stream_buffer.c.i
.PHONY : Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/stream_buffer.c.i

Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/stream_buffer.s: Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/stream_buffer.c.s
.PHONY : Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/stream_buffer.s

# target to generate assembly for a file
Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/stream_buffer.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/freertos_kernel.dir/build.make CMakeFiles/freertos_kernel.dir/Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/stream_buffer.c.s
.PHONY : Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/stream_buffer.c.s

Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/tasks.o: Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/tasks.c.o
.PHONY : Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/tasks.o

# target to build an object file
Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/tasks.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/freertos_kernel.dir/build.make CMakeFiles/freertos_kernel.dir/Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/tasks.c.o
.PHONY : Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/tasks.c.o

Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/tasks.i: Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/tasks.c.i
.PHONY : Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/tasks.i

# target to preprocess a source file
Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/tasks.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/freertos_kernel.dir/build.make CMakeFiles/freertos_kernel.dir/Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/tasks.c.i
.PHONY : Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/tasks.c.i

Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/tasks.s: Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/tasks.c.s
.PHONY : Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/tasks.s

# target to generate assembly for a file
Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/tasks.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/freertos_kernel.dir/build.make CMakeFiles/freertos_kernel.dir/Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/tasks.c.s
.PHONY : Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/tasks.c.s

Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/timers.o: Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/timers.c.o
.PHONY : Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/timers.o

# target to build an object file
Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/timers.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/freertos_kernel.dir/build.make CMakeFiles/freertos_kernel.dir/Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/timers.c.o
.PHONY : Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/timers.c.o

Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/timers.i: Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/timers.c.i
.PHONY : Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/timers.i

# target to preprocess a source file
Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/timers.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/freertos_kernel.dir/build.make CMakeFiles/freertos_kernel.dir/Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/timers.c.i
.PHONY : Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/timers.c.i

Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/timers.s: Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/timers.c.s
.PHONY : Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/timers.s

# target to generate assembly for a file
Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/timers.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/freertos_kernel.dir/build.make CMakeFiles/freertos_kernel.dir/Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/timers.c.s
.PHONY : Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/timers.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... codegen"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... freertos_kernel"
	@echo "... stm32.elf"
	@echo "... Drivers/BSP/Components/lis302dl/lis302dl.o"
	@echo "... Drivers/BSP/Components/lis302dl/lis302dl.i"
	@echo "... Drivers/BSP/Components/lis302dl/lis302dl.s"
	@echo "... Drivers/BSP/Components/lis3dsh/lis3dsh.o"
	@echo "... Drivers/BSP/Components/lis3dsh/lis3dsh.i"
	@echo "... Drivers/BSP/Components/lis3dsh/lis3dsh.s"
	@echo "... Drivers/BSP/STM32F4-Discovery/stm32f4_discovery.o"
	@echo "... Drivers/BSP/STM32F4-Discovery/stm32f4_discovery.i"
	@echo "... Drivers/BSP/STM32F4-Discovery/stm32f4_discovery.s"
	@echo "... Drivers/BSP/STM32F4-Discovery/stm32f4_discovery_accelerometer.o"
	@echo "... Drivers/BSP/STM32F4-Discovery/stm32f4_discovery_accelerometer.i"
	@echo "... Drivers/BSP/STM32F4-Discovery/stm32f4_discovery_accelerometer.s"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.o"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.i"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.s"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_adc.o"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_adc.i"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_adc.s"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_can.o"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_can.i"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_can.s"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.o"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.i"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.s"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_crc.o"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_crc.i"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_crc.s"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cryp.o"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cryp.i"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cryp.s"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dac.o"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dac.i"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dac.s"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dcmi.o"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dcmi.i"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dcmi.s"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma.o"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma.i"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma.s"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_eth.o"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_eth.i"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_eth.s"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash.o"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash.i"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash.s"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ex.o"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ex.i"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ex.s"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.o"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.i"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.s"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_hash.o"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_hash.i"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_hash.s"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_hcd.o"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_hcd.i"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_hcd.s"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2c.o"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2c.i"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2c.s"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2s.o"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2s.i"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2s.s"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_irda.o"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_irda.i"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_irda.s"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_iwdg.o"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_iwdg.i"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_iwdg.s"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_nand.o"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_nand.i"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_nand.s"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_nor.o"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_nor.i"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_nor.s"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pccard.o"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pccard.i"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pccard.s"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pcd.o"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pcd.i"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pcd.s"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pcd_ex.o"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pcd_ex.i"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pcd_ex.s"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr.o"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr.i"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr.s"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.o"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.i"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.s"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rng.o"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rng.i"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rng.s"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rtc.o"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rtc.i"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rtc.s"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_sd.o"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_sd.i"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_sd.s"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_smartcard.o"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_smartcard.i"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_smartcard.s"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_spi.o"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_spi.i"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_spi.s"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_sram.o"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_sram.i"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_sram.s"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim.o"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim.i"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim.s"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim_ex.o"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim_ex.i"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim_ex.s"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_uart.o"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_uart.i"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_uart.s"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_usart.o"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_usart.i"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_usart.s"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_wwdg.o"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_wwdg.i"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_wwdg.s"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_fsmc.o"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_fsmc.i"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_fsmc.s"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_sdmmc.o"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_sdmmc.i"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_sdmmc.s"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_usb.o"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_usb.i"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_usb.s"
	@echo "... STM32CubeIDE/Application/Startup/startup_stm32f407vgtx.o"
	@echo "... Src/main.o"
	@echo "... Src/main.i"
	@echo "... Src/main.s"
	@echo "... Src/stm32f4xx_hal_msp.o"
	@echo "... Src/stm32f4xx_hal_msp.i"
	@echo "... Src/stm32f4xx_hal_msp.s"
	@echo "... Src/stm32f4xx_it.o"
	@echo "... Src/stm32f4xx_it.i"
	@echo "... Src/stm32f4xx_it.s"
	@echo "... Src/syscalls.o"
	@echo "... Src/syscalls.i"
	@echo "... Src/syscalls.s"
	@echo "... Src/sysmem.o"
	@echo "... Src/sysmem.i"
	@echo "... Src/sysmem.s"
	@echo "... Src/system_stm32f4xx.o"
	@echo "... Src/system_stm32f4xx.i"
	@echo "... Src/system_stm32f4xx.s"
	@echo "... Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/croutine.o"
	@echo "... Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/croutine.i"
	@echo "... Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/croutine.s"
	@echo "... Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/event_groups.o"
	@echo "... Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/event_groups.i"
	@echo "... Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/event_groups.s"
	@echo "... Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/list.o"
	@echo "... Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/list.i"
	@echo "... Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/list.s"
	@echo "... Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/queue.o"
	@echo "... Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/queue.i"
	@echo "... Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/queue.s"
	@echo "... Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/stream_buffer.o"
	@echo "... Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/stream_buffer.i"
	@echo "... Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/stream_buffer.s"
	@echo "... Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/tasks.o"
	@echo "... Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/tasks.i"
	@echo "... Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/tasks.s"
	@echo "... Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/timers.o"
	@echo "... Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/timers.i"
	@echo "... Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/FreeRTOS/FreeRTOS/Source/timers.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

