# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/Demonstrations

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/Demonstrations

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/Demonstrations/CMakeFiles /Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/Demonstrations//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/Demonstrations/CMakeFiles 0
.PHONY : all

# The main codegen target
codegen: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/Demonstrations/CMakeFiles /Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/Demonstrations//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 codegen
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/charlesmurphy/STM32CubeIDE/workspace_1.18.0/Demonstrations/CMakeFiles 0
.PHONY : codegen

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named freertos_kernel

# Build rule for target.
freertos_kernel: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 freertos_kernel
.PHONY : freertos_kernel

# fast build rule for target.
freertos_kernel/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/freertos_kernel.dir/build.make CMakeFiles/freertos_kernel.dir/build
.PHONY : freertos_kernel/fast

#=============================================================================
# Target rules for targets named stm32.elf

# Build rule for target.
stm32.elf: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 stm32.elf
.PHONY : stm32.elf

# fast build rule for target.
stm32.elf/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/build
.PHONY : stm32.elf/fast

#=============================================================================
# Target rules for targets named analysis

# Build rule for target.
analysis: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 analysis
.PHONY : analysis

# fast build rule for target.
analysis/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/analysis.dir/build.make CMakeFiles/analysis.dir/build
.PHONY : analysis/fast

Drivers/BSP/Components/lis302dl/lis302dl.o: Drivers/BSP/Components/lis302dl/lis302dl.c.o
.PHONY : Drivers/BSP/Components/lis302dl/lis302dl.o

# target to build an object file
Drivers/BSP/Components/lis302dl/lis302dl.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/BSP/Components/lis302dl/lis302dl.c.o
.PHONY : Drivers/BSP/Components/lis302dl/lis302dl.c.o

Drivers/BSP/Components/lis302dl/lis302dl.i: Drivers/BSP/Components/lis302dl/lis302dl.c.i
.PHONY : Drivers/BSP/Components/lis302dl/lis302dl.i

# target to preprocess a source file
Drivers/BSP/Components/lis302dl/lis302dl.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/BSP/Components/lis302dl/lis302dl.c.i
.PHONY : Drivers/BSP/Components/lis302dl/lis302dl.c.i

Drivers/BSP/Components/lis302dl/lis302dl.s: Drivers/BSP/Components/lis302dl/lis302dl.c.s
.PHONY : Drivers/BSP/Components/lis302dl/lis302dl.s

# target to generate assembly for a file
Drivers/BSP/Components/lis302dl/lis302dl.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/BSP/Components/lis302dl/lis302dl.c.s
.PHONY : Drivers/BSP/Components/lis302dl/lis302dl.c.s

Drivers/BSP/Components/lis3dsh/lis3dsh.o: Drivers/BSP/Components/lis3dsh/lis3dsh.c.o
.PHONY : Drivers/BSP/Components/lis3dsh/lis3dsh.o

# target to build an object file
Drivers/BSP/Components/lis3dsh/lis3dsh.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/BSP/Components/lis3dsh/lis3dsh.c.o
.PHONY : Drivers/BSP/Components/lis3dsh/lis3dsh.c.o

Drivers/BSP/Components/lis3dsh/lis3dsh.i: Drivers/BSP/Components/lis3dsh/lis3dsh.c.i
.PHONY : Drivers/BSP/Components/lis3dsh/lis3dsh.i

# target to preprocess a source file
Drivers/BSP/Components/lis3dsh/lis3dsh.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/BSP/Components/lis3dsh/lis3dsh.c.i
.PHONY : Drivers/BSP/Components/lis3dsh/lis3dsh.c.i

Drivers/BSP/Components/lis3dsh/lis3dsh.s: Drivers/BSP/Components/lis3dsh/lis3dsh.c.s
.PHONY : Drivers/BSP/Components/lis3dsh/lis3dsh.s

# target to generate assembly for a file
Drivers/BSP/Components/lis3dsh/lis3dsh.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/BSP/Components/lis3dsh/lis3dsh.c.s
.PHONY : Drivers/BSP/Components/lis3dsh/lis3dsh.c.s

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.o: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.c.o
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.o

# target to build an object file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.c.o
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.c.o

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.i: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.c.i
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.i

# target to preprocess a source file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.c.i
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.c.i

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.s: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.c.s
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.s

# target to generate assembly for a file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.c.s
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.c.s

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_adc.o: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_adc.c.o
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_adc.o

# target to build an object file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_adc.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_adc.c.o
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_adc.c.o

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_adc.i: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_adc.c.i
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_adc.i

# target to preprocess a source file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_adc.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_adc.c.i
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_adc.c.i

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_adc.s: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_adc.c.s
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_adc.s

# target to generate assembly for a file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_adc.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_adc.c.s
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_adc.c.s

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_can.o: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_can.c.o
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_can.o

# target to build an object file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_can.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_can.c.o
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_can.c.o

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_can.i: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_can.c.i
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_can.i

# target to preprocess a source file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_can.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_can.c.i
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_can.c.i

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_can.s: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_can.c.s
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_can.s

# target to generate assembly for a file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_can.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_can.c.s
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_can.c.s

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.o: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.c.o
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.o

# target to build an object file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.c.o
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.c.o

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.i: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.c.i
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.i

# target to preprocess a source file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.c.i
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.c.i

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.s: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.c.s
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.s

# target to generate assembly for a file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.c.s
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.c.s

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_exti.o: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_exti.c.o
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_exti.o

# target to build an object file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_exti.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_exti.c.o
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_exti.c.o

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_exti.i: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_exti.c.i
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_exti.i

# target to preprocess a source file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_exti.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_exti.c.i
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_exti.c.i

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_exti.s: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_exti.c.s
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_exti.s

# target to generate assembly for a file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_exti.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_exti.c.s
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_exti.c.s

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.o: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.c.o
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.o

# target to build an object file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.c.o
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.c.o

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.i: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.c.i
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.i

# target to preprocess a source file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.c.i
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.c.i

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.s: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.c.s
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.s

# target to generate assembly for a file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.c.s
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.c.s

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr.o: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr.c.o
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr.o

# target to build an object file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr.c.o
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr.c.o

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr.i: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr.c.i
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr.i

# target to preprocess a source file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr.c.i
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr.c.i

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr.s: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr.c.s
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr.s

# target to generate assembly for a file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr.c.s
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr.c.s

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.o: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.c.o
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.o

# target to build an object file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.c.o
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.c.o

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.i: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.c.i
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.i

# target to preprocess a source file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.c.i
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.c.i

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.s: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.c.s
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.s

# target to generate assembly for a file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.c.s
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.c.s

FreeRTOS/croutine.o: FreeRTOS/croutine.c.o
.PHONY : FreeRTOS/croutine.o

# target to build an object file
FreeRTOS/croutine.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/freertos_kernel.dir/build.make CMakeFiles/freertos_kernel.dir/FreeRTOS/croutine.c.o
.PHONY : FreeRTOS/croutine.c.o

FreeRTOS/croutine.i: FreeRTOS/croutine.c.i
.PHONY : FreeRTOS/croutine.i

# target to preprocess a source file
FreeRTOS/croutine.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/freertos_kernel.dir/build.make CMakeFiles/freertos_kernel.dir/FreeRTOS/croutine.c.i
.PHONY : FreeRTOS/croutine.c.i

FreeRTOS/croutine.s: FreeRTOS/croutine.c.s
.PHONY : FreeRTOS/croutine.s

# target to generate assembly for a file
FreeRTOS/croutine.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/freertos_kernel.dir/build.make CMakeFiles/freertos_kernel.dir/FreeRTOS/croutine.c.s
.PHONY : FreeRTOS/croutine.c.s

FreeRTOS/event_groups.o: FreeRTOS/event_groups.c.o
.PHONY : FreeRTOS/event_groups.o

# target to build an object file
FreeRTOS/event_groups.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/freertos_kernel.dir/build.make CMakeFiles/freertos_kernel.dir/FreeRTOS/event_groups.c.o
.PHONY : FreeRTOS/event_groups.c.o

FreeRTOS/event_groups.i: FreeRTOS/event_groups.c.i
.PHONY : FreeRTOS/event_groups.i

# target to preprocess a source file
FreeRTOS/event_groups.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/freertos_kernel.dir/build.make CMakeFiles/freertos_kernel.dir/FreeRTOS/event_groups.c.i
.PHONY : FreeRTOS/event_groups.c.i

FreeRTOS/event_groups.s: FreeRTOS/event_groups.c.s
.PHONY : FreeRTOS/event_groups.s

# target to generate assembly for a file
FreeRTOS/event_groups.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/freertos_kernel.dir/build.make CMakeFiles/freertos_kernel.dir/FreeRTOS/event_groups.c.s
.PHONY : FreeRTOS/event_groups.c.s

FreeRTOS/list.o: FreeRTOS/list.c.o
.PHONY : FreeRTOS/list.o

# target to build an object file
FreeRTOS/list.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/freertos_kernel.dir/build.make CMakeFiles/freertos_kernel.dir/FreeRTOS/list.c.o
.PHONY : FreeRTOS/list.c.o

FreeRTOS/list.i: FreeRTOS/list.c.i
.PHONY : FreeRTOS/list.i

# target to preprocess a source file
FreeRTOS/list.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/freertos_kernel.dir/build.make CMakeFiles/freertos_kernel.dir/FreeRTOS/list.c.i
.PHONY : FreeRTOS/list.c.i

FreeRTOS/list.s: FreeRTOS/list.c.s
.PHONY : FreeRTOS/list.s

# target to generate assembly for a file
FreeRTOS/list.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/freertos_kernel.dir/build.make CMakeFiles/freertos_kernel.dir/FreeRTOS/list.c.s
.PHONY : FreeRTOS/list.c.s

FreeRTOS/queue.o: FreeRTOS/queue.c.o
.PHONY : FreeRTOS/queue.o

# target to build an object file
FreeRTOS/queue.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/freertos_kernel.dir/build.make CMakeFiles/freertos_kernel.dir/FreeRTOS/queue.c.o
.PHONY : FreeRTOS/queue.c.o

FreeRTOS/queue.i: FreeRTOS/queue.c.i
.PHONY : FreeRTOS/queue.i

# target to preprocess a source file
FreeRTOS/queue.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/freertos_kernel.dir/build.make CMakeFiles/freertos_kernel.dir/FreeRTOS/queue.c.i
.PHONY : FreeRTOS/queue.c.i

FreeRTOS/queue.s: FreeRTOS/queue.c.s
.PHONY : FreeRTOS/queue.s

# target to generate assembly for a file
FreeRTOS/queue.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/freertos_kernel.dir/build.make CMakeFiles/freertos_kernel.dir/FreeRTOS/queue.c.s
.PHONY : FreeRTOS/queue.c.s

FreeRTOS/stream_buffer.o: FreeRTOS/stream_buffer.c.o
.PHONY : FreeRTOS/stream_buffer.o

# target to build an object file
FreeRTOS/stream_buffer.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/freertos_kernel.dir/build.make CMakeFiles/freertos_kernel.dir/FreeRTOS/stream_buffer.c.o
.PHONY : FreeRTOS/stream_buffer.c.o

FreeRTOS/stream_buffer.i: FreeRTOS/stream_buffer.c.i
.PHONY : FreeRTOS/stream_buffer.i

# target to preprocess a source file
FreeRTOS/stream_buffer.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/freertos_kernel.dir/build.make CMakeFiles/freertos_kernel.dir/FreeRTOS/stream_buffer.c.i
.PHONY : FreeRTOS/stream_buffer.c.i

FreeRTOS/stream_buffer.s: FreeRTOS/stream_buffer.c.s
.PHONY : FreeRTOS/stream_buffer.s

# target to generate assembly for a file
FreeRTOS/stream_buffer.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/freertos_kernel.dir/build.make CMakeFiles/freertos_kernel.dir/FreeRTOS/stream_buffer.c.s
.PHONY : FreeRTOS/stream_buffer.c.s

FreeRTOS/tasks.o: FreeRTOS/tasks.c.o
.PHONY : FreeRTOS/tasks.o

# target to build an object file
FreeRTOS/tasks.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/freertos_kernel.dir/build.make CMakeFiles/freertos_kernel.dir/FreeRTOS/tasks.c.o
.PHONY : FreeRTOS/tasks.c.o

FreeRTOS/tasks.i: FreeRTOS/tasks.c.i
.PHONY : FreeRTOS/tasks.i

# target to preprocess a source file
FreeRTOS/tasks.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/freertos_kernel.dir/build.make CMakeFiles/freertos_kernel.dir/FreeRTOS/tasks.c.i
.PHONY : FreeRTOS/tasks.c.i

FreeRTOS/tasks.s: FreeRTOS/tasks.c.s
.PHONY : FreeRTOS/tasks.s

# target to generate assembly for a file
FreeRTOS/tasks.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/freertos_kernel.dir/build.make CMakeFiles/freertos_kernel.dir/FreeRTOS/tasks.c.s
.PHONY : FreeRTOS/tasks.c.s

FreeRTOS/timers.o: FreeRTOS/timers.c.o
.PHONY : FreeRTOS/timers.o

# target to build an object file
FreeRTOS/timers.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/freertos_kernel.dir/build.make CMakeFiles/freertos_kernel.dir/FreeRTOS/timers.c.o
.PHONY : FreeRTOS/timers.c.o

FreeRTOS/timers.i: FreeRTOS/timers.c.i
.PHONY : FreeRTOS/timers.i

# target to preprocess a source file
FreeRTOS/timers.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/freertos_kernel.dir/build.make CMakeFiles/freertos_kernel.dir/FreeRTOS/timers.c.i
.PHONY : FreeRTOS/timers.c.i

FreeRTOS/timers.s: FreeRTOS/timers.c.s
.PHONY : FreeRTOS/timers.s

# target to generate assembly for a file
FreeRTOS/timers.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/freertos_kernel.dir/build.make CMakeFiles/freertos_kernel.dir/FreeRTOS/timers.c.s
.PHONY : FreeRTOS/timers.c.s

Src/main.o: Src/main.c.o
.PHONY : Src/main.o

# target to build an object file
Src/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Src/main.c.o
.PHONY : Src/main.c.o

Src/main.i: Src/main.c.i
.PHONY : Src/main.i

# target to preprocess a source file
Src/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Src/main.c.i
.PHONY : Src/main.c.i

Src/main.s: Src/main.c.s
.PHONY : Src/main.s

# target to generate assembly for a file
Src/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Src/main.c.s
.PHONY : Src/main.c.s

Src/port.o: Src/port.c.o
.PHONY : Src/port.o

# target to build an object file
Src/port.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Src/port.c.o
.PHONY : Src/port.c.o

Src/port.i: Src/port.c.i
.PHONY : Src/port.i

# target to preprocess a source file
Src/port.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Src/port.c.i
.PHONY : Src/port.c.i

Src/port.s: Src/port.c.s
.PHONY : Src/port.s

# target to generate assembly for a file
Src/port.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Src/port.c.s
.PHONY : Src/port.c.s

Src/stm32f4xx_hal_msp.o: Src/stm32f4xx_hal_msp.c.o
.PHONY : Src/stm32f4xx_hal_msp.o

# target to build an object file
Src/stm32f4xx_hal_msp.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Src/stm32f4xx_hal_msp.c.o
.PHONY : Src/stm32f4xx_hal_msp.c.o

Src/stm32f4xx_hal_msp.i: Src/stm32f4xx_hal_msp.c.i
.PHONY : Src/stm32f4xx_hal_msp.i

# target to preprocess a source file
Src/stm32f4xx_hal_msp.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Src/stm32f4xx_hal_msp.c.i
.PHONY : Src/stm32f4xx_hal_msp.c.i

Src/stm32f4xx_hal_msp.s: Src/stm32f4xx_hal_msp.c.s
.PHONY : Src/stm32f4xx_hal_msp.s

# target to generate assembly for a file
Src/stm32f4xx_hal_msp.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Src/stm32f4xx_hal_msp.c.s
.PHONY : Src/stm32f4xx_hal_msp.c.s

Src/syscalls.o: Src/syscalls.c.o
.PHONY : Src/syscalls.o

# target to build an object file
Src/syscalls.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Src/syscalls.c.o
.PHONY : Src/syscalls.c.o

Src/syscalls.i: Src/syscalls.c.i
.PHONY : Src/syscalls.i

# target to preprocess a source file
Src/syscalls.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Src/syscalls.c.i
.PHONY : Src/syscalls.c.i

Src/syscalls.s: Src/syscalls.c.s
.PHONY : Src/syscalls.s

# target to generate assembly for a file
Src/syscalls.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Src/syscalls.c.s
.PHONY : Src/syscalls.c.s

Src/sysmem.o: Src/sysmem.c.o
.PHONY : Src/sysmem.o

# target to build an object file
Src/sysmem.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Src/sysmem.c.o
.PHONY : Src/sysmem.c.o

Src/sysmem.i: Src/sysmem.c.i
.PHONY : Src/sysmem.i

# target to preprocess a source file
Src/sysmem.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Src/sysmem.c.i
.PHONY : Src/sysmem.c.i

Src/sysmem.s: Src/sysmem.c.s
.PHONY : Src/sysmem.s

# target to generate assembly for a file
Src/sysmem.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Src/sysmem.c.s
.PHONY : Src/sysmem.c.s

Src/system_stm32f4xx.o: Src/system_stm32f4xx.c.o
.PHONY : Src/system_stm32f4xx.o

# target to build an object file
Src/system_stm32f4xx.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Src/system_stm32f4xx.c.o
.PHONY : Src/system_stm32f4xx.c.o

Src/system_stm32f4xx.i: Src/system_stm32f4xx.c.i
.PHONY : Src/system_stm32f4xx.i

# target to preprocess a source file
Src/system_stm32f4xx.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Src/system_stm32f4xx.c.i
.PHONY : Src/system_stm32f4xx.c.i

Src/system_stm32f4xx.s: Src/system_stm32f4xx.c.s
.PHONY : Src/system_stm32f4xx.s

# target to generate assembly for a file
Src/system_stm32f4xx.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Src/system_stm32f4xx.c.s
.PHONY : Src/system_stm32f4xx.c.s

Startup/startup_stm32f407vgtx.o: Startup/startup_stm32f407vgtx.s.o
.PHONY : Startup/startup_stm32f407vgtx.o

# target to build an object file
Startup/startup_stm32f407vgtx.s.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32.elf.dir/build.make CMakeFiles/stm32.elf.dir/Startup/startup_stm32f407vgtx.s.o
.PHONY : Startup/startup_stm32f407vgtx.s.o

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... codegen"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... analysis"
	@echo "... freertos_kernel"
	@echo "... stm32.elf"
	@echo "... Drivers/BSP/Components/lis302dl/lis302dl.o"
	@echo "... Drivers/BSP/Components/lis302dl/lis302dl.i"
	@echo "... Drivers/BSP/Components/lis302dl/lis302dl.s"
	@echo "... Drivers/BSP/Components/lis3dsh/lis3dsh.o"
	@echo "... Drivers/BSP/Components/lis3dsh/lis3dsh.i"
	@echo "... Drivers/BSP/Components/lis3dsh/lis3dsh.s"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.o"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.i"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.s"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_adc.o"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_adc.i"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_adc.s"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_can.o"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_can.i"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_can.s"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.o"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.i"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.s"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_exti.o"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_exti.i"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_exti.s"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.o"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.i"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.s"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr.o"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr.i"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr.s"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.o"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.i"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.s"
	@echo "... FreeRTOS/croutine.o"
	@echo "... FreeRTOS/croutine.i"
	@echo "... FreeRTOS/croutine.s"
	@echo "... FreeRTOS/event_groups.o"
	@echo "... FreeRTOS/event_groups.i"
	@echo "... FreeRTOS/event_groups.s"
	@echo "... FreeRTOS/list.o"
	@echo "... FreeRTOS/list.i"
	@echo "... FreeRTOS/list.s"
	@echo "... FreeRTOS/queue.o"
	@echo "... FreeRTOS/queue.i"
	@echo "... FreeRTOS/queue.s"
	@echo "... FreeRTOS/stream_buffer.o"
	@echo "... FreeRTOS/stream_buffer.i"
	@echo "... FreeRTOS/stream_buffer.s"
	@echo "... FreeRTOS/tasks.o"
	@echo "... FreeRTOS/tasks.i"
	@echo "... FreeRTOS/tasks.s"
	@echo "... FreeRTOS/timers.o"
	@echo "... FreeRTOS/timers.i"
	@echo "... FreeRTOS/timers.s"
	@echo "... Src/main.o"
	@echo "... Src/main.i"
	@echo "... Src/main.s"
	@echo "... Src/port.o"
	@echo "... Src/port.i"
	@echo "... Src/port.s"
	@echo "... Src/stm32f4xx_hal_msp.o"
	@echo "... Src/stm32f4xx_hal_msp.i"
	@echo "... Src/stm32f4xx_hal_msp.s"
	@echo "... Src/syscalls.o"
	@echo "... Src/syscalls.i"
	@echo "... Src/syscalls.s"
	@echo "... Src/sysmem.o"
	@echo "... Src/sysmem.i"
	@echo "... Src/sysmem.s"
	@echo "... Src/system_stm32f4xx.o"
	@echo "... Src/system_stm32f4xx.i"
	@echo "... Src/system_stm32f4xx.s"
	@echo "... Startup/startup_stm32f407vgtx.o"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

